# general settings
name: train_FSPS1
model_type: FSPS1Model
scale: 1
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 8 GPUs
manual_seed: 0

# dataset and data loader settings图像域 [4,6,8,6]（如果需要处理图像域）：
datasets:
  train:
    name: TrainSet
    type: DeblurPairedDataset
    dataroot_gt: /SSD_8T/彭鹏/数据/allfentu/train
    dataroot_lq: /SSD_8T/彭鹏/数据/allfentu2000/train
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk


    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    mini_batch_sizes: [4,2,2,2,1,1]             # Batch size per gpu   
    iters: [500,500,500,400,200,200]
    gt_size: 512   # Max patch size for progressive training
    gt_sizes: [192, 256,320,384,464,512]  # Patch sizes for progressive training.

    # mini_batch_sizes: [8,4,2,2,1,1]
    # iters: [92000,80000,38000,33000,33000,24000]
    # gt_size: 512
    # gt_sizes: [192, 256,320,384,464,512]
    # num_worker_per_gpu: 8
    # batch_size_per_gpu: 1
    # mini_batch_sizes: [1]             # Batch size per gpu   
    # iters: [30000]
    # gt_size: 512   # Max patch size for progressive training
    # gt_sizes: [512]  # Patch sizes for progressive training.



    # data loader
    use_shuffle: true
    dataset_enlarge_ratio: 1
    prefetch_mode: cpu

  # Uncomment these for validation
  val:
    name: ValSet
    type: DeblurPairedDataset
    dataroot_gt: /SSD_8T/彭鹏/数据/allfentu/val
    dataroot_lq: /SSD_8T/彭鹏/数据/allfentu2000/val
    io_backend:
      type: disk

# network structures
# network_g:
#   type: FSPS1
#   n_encoder_res: 5
#   inp_channels: 3
#   out_channels: 3
#   dim: 48
#   num_blocks: [6,5,5,4]
#   num_refinement_blocks: 4
#   heads: [1,2,4,8]
#   ffn_expansion_factor: 2
#   bias: False
#   LayerNorm_type: WithBias

# network structures
network_g:
  type: FSPS1
  n_encoder_res: 5
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [6,5,5,4]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2
  bias: False
  LayerNorm_type: WithBias

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~ 

# training settings
train:
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [30000, 98000]       
    restart_weights: [1,1]
    eta_mins: [0.000285,0.000001]  

  total_iter: 300000
  warmup_iter: -1  # no warm up

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  mse_opt:
    type: MSELoss
    loss_weight: 0
    reduction: mean
  ssim_opt:
    type: SSIMLoss
    loss_weight: 0.3
    reduction: mean

# Uncomment these for validation
# validation settings
val:
  val_freq: !!float 2e2
  save_img: False

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 400
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
